### ISSUE TITLE
Entities and assets don't get linked when using multiple locales

### ISSUE THREAD

**Issue by frankmarineau** [contentful/contentful_middleman#95]
If I add `locales: '*'` to the CDA query, assets and links will only show the `sys` key and won't be populated with the actual linked resource. In the following example, I'm using two locales (en-us and fr-CA) and two content types: a *Section* that contains multiple *Topic*s

Here's the generated yml I get for a *Section* if I don't specify multiple locales in the CDA query (`f.cda_query = {}`):

```yaml
---
:id: 1RU28gignOCGg0UMau0mcM
:title: Life
:topics:
- :id: 5Hf7MhcNaw4OWoAWKYWa6M
  :question: Why?
  :answer: Because
```

💯 . The associated *Topic*s are populated.

Here is what I get when I set `f.cda_query = { locales: '*' }`:

```yaml
---
:id: 1RU28gignOCGg0UMau0mcM
:title:
  :en-US: Life
  :fr-CA: La vie
:topics:
  :en-US:
  - sys:
      type: Link
      linkType: Entry
      id: 5Hf7MhcNaw4OWoAWKYWa6M
```

It loads plain fields just fine (the title), but linked entries are no longer populated.

For reference, here's what one of the *Topic* yml files looks like:

```yaml
---
:id: 1RU28gignOCGg0UMau0mcM
:title:
  :en-US: Life
  :fr-CA: La vie
:topics:
- :id: 5Hf7MhcNaw4OWoAWKYWa6M
  :en-US:
    :question: Why?
    :answer: Because
  :fr-CA:
    :question: Pourquoi?
    :answer: Parce que
```

It's not shown in the above example, but the same issue happens with linked assets.

### Additional information
- Ruby 2.2.3
- Middleman 3.4.1
- Latest published contentful_middleman (also tried with both contentful.rb and this repo's `master`)
- Tried with these two content type settings:
  - i18n enabled on the *Section* "topics" one-to-many reference field and i18n disabled on the *Topic* fields (question and answer)
  - i18n disabled on the "topics" reference but enabled on *Topic*'s fields.

Any idea how to solve this? Thanks!

**Comment by dlitvakb** [comment]
Hey @frankmarineau,

Looks like there is an issue with link resolution for localized content.

I will look into it next week (I'm on vacation until Monday).

In the meantime, you can solve the links locally by filtering in the views.

Cheers

**Comment by frankmarineau** [comment]
Thanks a lot @dlitvakb!

**Comment by martzoukos** [comment]
Hey there,

I'm also currently facing this issue and try to filter the entries in the views but I'm having some trouble with fetching linked assets.

I have a content_type named `block_images` and a typical response includes something like that:
```
:id: 2xsRcbi9tiUcGG84eKYywM
:name:
  :de-DE: List of Images
:images:
  :de-DE:
  - sys:
      type: Link
      linkType: Asset
      id: 3xTPCFNqbSsAyKEUGcOoyy
  - sys:
      type: Link
      linkType: Asset
      id: 5y2zucqvnigog20eMGaIQi
  - sys:
      type: Link
      linkType: Asset
      id: 53yAt8gfOMee6akGUe4m06
  - sys:
      type: Link
      linkType: Asset
      id: 1yUI3W7JqMOUGiCckcqkE0

```
How can I access the information of these linked Assets? I tried maybe fetching them locally by passing the following:

```
  f.content_types = {
    ...
    assets: 'Assets'
  }
```
but that doesn't work.

Any ideas about that?

Thank you very much in advance!
